version: '3.8'

services:
  apex-map-bot:
    build: .
    container_name: apex-map-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=apex-map-bot"
      - "description=Apex Legends Map Rotation Discord Bot"
      
  # Auto-updater that checks for changes every 5 minutes
  watchtower:
    image: containrrr/watchtower
    container_name: apex-bot-updater
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300  # Check every 5 minutes
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
    command: apex-map-bot

networks:
  bot-network:
    driver: bridge
